# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
        show-channel-urls: true

    - name: configure conda and install code
      shell: bash -l {0}
      run: |
        conda config --set always_yes yes
        conda install -q mamba
        mamba install -q \
        flake8 \
        pytest \
        numpy \
        jax \
        fitsio

        pip install -e --no-deps .


    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        flake8 lenspt

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        source lenspt_config
        pytest
